const projects = [
    {
      '_id': '1',
      'project_name': 'Project management software for marketing, media, and advertising',
      'project_description':
        'Key features include planning and adjusting whos working on what, timelines, and budgets; real-time messaging and collaboration; and tracking project health and project performance.',
      'status': 'Ongoing',
      'hours_consumed': '134',
      'start_date': 'February 1, 2026',
      'end_date': 'August 30, 2026',
      'task_description': '',
      'task_name': '',
      'task_status': '',
      'task_hours_consumed': '',
      'user_assigned': '',
      'task_start_date': '',
      'task_end_date': '',
    },
    {
      '_id': '2',
      'project_name': 'Project management software for software development and IT',
      'project_description':
        'Key features here are bug tracking and issue management, backlog planning and maintenance, and storage for documentation, team wikis, and knowledge bases.',
      'status': 'Finished',
      'hours_consumed': '264',
      'start_date': 'December 11, 2025',
      'end_date': 'February 5, 2026',
      'task_description': '',
      'task_name': '',
      'task_status': '',
      'task_hours_consumed': '',
      'user_assigned': '',
      'task_start_date': '',
      'task_end_date': '',
    },
    {
      '_id': '3',
      'project_name': 'Project management software for construction',
      'project_description':
        'Features include Gantt charts and critical path capabilities; allocating and tracking utilization of labor, equipment, and materials; and quality management and compliance.',
      'status': 'Late',
      'hours_consumed': '398',
      'start_date': 'October 1, 2025',
      'end_date': 'February 1, 2026',
      'task_description': '',
      'task_name': '',
      'task_status': '',
      'task_hours_consumed': '',
      'user_assigned': '',
      'task_start_date': '',
      'task_end_date': '',
    },
    {
      '_id': '4',
      'project_name': 'Project management software for financial services',
      'project_description':
        'Key features here are identifying and mitigating risks; planning, managing, and tracking entire portfolios of projects; and tools for managing vendors and suppliers.',
      'status': 'Ongoing',
      'hours_consumed': '213',
      'start_date': 'January 10, 2026',
      'end_date': 'April 1, 2026',
      'task_description': '',
      'task_name': '',
      'task_status': '',
      'task_hours_consumed': '',
      'user_assigned': '',
      'task_start_date': '',
      'task_end_date': '',
    },
    {
      '_id': '5',
      'project_name': 'Project management software for healthcare',
      'project_description':
        'Features for scheduling and managing staff, equipment, and facilities; identifying and monitoring risks; and storage and management features for healthcare documents and resources.',
      'status': 'Ongoing',
      'hours_consumed': '78',
      'start_date': 'January 25, 2026',
      'end_date': 'November 20, 2026',
      'task_description': '',
      'task_name': '',
      'task_status': '',
      'task_hours_consumed': '',
      'user_assigned': '',
      'task_start_date': '',
      'task_end_date': '',
    },
  ]
  
  
  export default projects